package agent

import (
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/gorilla/websocket"
	"github.com/kubestellar/console/pkg/agent/protocol"
	"github.com/kubestellar/console/pkg/k8s"
	"github.com/kubestellar/console/pkg/safego"
	"github.com/kubestellar/console/pkg/settings"
)

const (
	agentDefaultTimeout  = 30 * time.Second
	agentExtendedTimeout = 60 * time.Second
	agentCommandTimeout  = 45 * time.Second
	healthCheckTimeout   = 2 * time.Second
	registryTimeout      = 10 * time.Second
	consoleHealthTimeout = 5 * time.Second
	wsPingInterval       = 5 * time.Second  // how often to send WebSocket pings (adaptive heartbeat #14192)
	wsPongTimeout        = 15 * time.Second // how long to wait for a pong before declaring dead (adaptive #14192)
	wsWriteTimeout       = 10 * time.Second // deadline for a single write (prevents blocking on dead conn)
	stabilizationDelay   = 3 * time.Second
	startupDelay         = 500 * time.Millisecond
	metricsHistoryTick   = 10 * time.Minute
	agentFileMode        = 0600

	// Backend port resolution constants (see resolveBackendPort in server_http.go).
	// These are duplicated from cmd/watcher/watcher.go because pkg/agent cannot
	// import the main package. Keep them in sync with watcher.go.
	backendPortWatchdogMode  = 8081 // watchdog (8080) proxies -> backend (8081)
	backendPortLegacyDefault = 8080 // no-watchdog deployments: backend binds 8080 directly
	watchdogPidFilePath      = "/tmp/.kc-watchdog.pid"
	backendHealthScheme      = "http"
	backendHealthHost        = "127.0.0.1"
	backendHealthPath        = "/health"
	backendPortEnvVar        = "BACKEND_PORT"

	maxQueryLimit       = 1000    // Upper bound for client-supplied limit query parameter
	maxRequestBodyBytes = 1 << 20 // 1MB upper bound for request body reads

	// autoGeneratedTokenBytes is the number of random bytes used to generate
	// an agent token when KC_AGENT_TOKEN is not set (#9480). 32 bytes yields
	// a 64-character hex string — sufficient entropy for a local auth secret.
	autoGeneratedTokenBytes = 32

	// defaultSessionTokenQuota is the maximum total tokens (input + output)
	// allowed per agent session before new prompts are rejected. Prevents
	// bill-shock from runaway or malicious clients (#9438). Configurable
	// via KC_SESSION_TOKEN_QUOTA env var. 0 = unlimited. Default: 5 million.
	defaultSessionTokenQuota int64 = 5_000_000

	// sessionTokenQuotaEnvVar is the environment variable operators can set
	// to override the per-session aggregate token limit.
	sessionTokenQuotaEnvVar = "KC_SESSION_TOKEN_QUOTA"

	// deployedByAnonymousMarker is the default value recorded on workloads
	// created via kc-agent when the caller did not supply a "deployedBy"
	// identifier. Matches pkg/k8s/workload.go DeployOptions default
	// ("anonymous") so resources created via either path look identical.
	deployedByAnonymousMarker = "anonymous"

	// defaultMissionExecutionTimeout is the compiled default for mission
	// execution.  Operators can override it at startup via the
	// KC_MISSION_TIMEOUT environment variable (accepts Go duration strings
	// such as "10m", "600s", "1h").  See #9482.
	// Increased from 5m to 15m to account for missions with multiple
	// workloads — cumulative installation time was causing the last
	// workload to timeout (#15165).
	defaultMissionExecutionTimeout = 15 * time.Minute

	// missionTimeoutEnvVar is the environment variable operators can set
	// to override the per-mission execution timeout.
	missionTimeoutEnvVar = "KC_MISSION_TIMEOUT"

	// missionHeartbeatInterval is how often the backend sends a heartbeat
	// progress event during mission execution.  This prevents the frontend's
	// stream-inactivity timer (90s) from firing during legitimate long-running
	// tool calls (e.g., `drasi init`, `helm install`) that produce no output
	// for extended periods.
	missionHeartbeatInterval = 30 * time.Second

	// handleChatMessageTimeout is the hard deadline for the non-streaming
	// handleChatMessage path (#6678). Previously this path passed
	// context.Background() to provider.Chat, meaning a hung AI provider
	// could permanently block the WebSocket read-loop goroutine and
	// prevent the client from ever receiving an error. 30s is enough for
	// the short-form non-streaming case while bounding worst-case wedge
	// time.  Streaming missions continue to use the longer
	// missionExecutionTimeout because they intentionally run tools.
	handleChatMessageTimeout = 30 * time.Second
)

// Version is set by ldflags during build
var Version = "dev"

// CommitSHA is set by ldflags during build (git commit hash)
var CommitSHA = "unknown"

// BuildTime is set by ldflags during build (ISO 8601 timestamp)
var BuildTime = "unknown"

// EventProcessor is a callback interface for processing k8s events in real-time.
// Stellar implements this to integrate with the console's event pipeline.
type EventProcessor interface {
	ProcessEvent(ctx context.Context, cluster, namespace, name, kind, reason, message, eventType string, count int32)
}

// Config holds agent configuration
type Config struct {
	Port           int
	Kubeconfig     string
	AllowedOrigins []string // Additional allowed origins (from --allowed-origins flag)
}

// AllowedOrigins for WebSocket connections (can be extended via env var)
var defaultAllowedOrigins = []string{
	"http://localhost",
	"https://localhost",
	"http://127.0.0.1",
	"https://127.0.0.1",
	// Known deployment URLs
	"https://console.kubestellar.io",
	"http://console.kubestellar.io",
	// Wildcard: any *.ibm.com subdomain (OpenShift routes, etc.)
	"https://*.ibm.com",
	"http://*.ibm.com",
}

// wsClient wraps a WebSocket connection with a per-connection write mutex
// to prevent gorilla/websocket panics from concurrent writes without
// requiring a global lock across all clients.
type wsClient struct {
	writeMu sync.Mutex
}

// Server is the local agent WebSocket server
type Server struct {
	config         Config
	upgrader       websocket.Upgrader
	kubectl        *KubectlProxy
	k8sClient      *k8s.MultiClusterClient // For rich cluster data queries
	registry       *Registry
	clients        map[*websocket.Conn]*wsClient
	clientsMux     sync.RWMutex
	allowedOrigins []string
	agentToken     string // Optional shared secret for authentication
	tokenExplicit  bool   // true when KC_AGENT_TOKEN was explicitly set (not auto-generated)

	// Token tracking
	tokenMux          sync.RWMutex
	tokenFileMux      sync.Mutex  // serializes file I/O in saveTokenUsage to prevent race (#9441)
	tokenFlushTimer   *time.Timer // debounced flush timer for batched disk writes (#9483)
	sessionStart      time.Time
	sessionTokensIn   int64
	sessionTokensOut  int64
	todayTokensIn     int64
	todayTokensOut    int64
	todayDate         string // YYYY-MM-DD format to detect day change
	lastSavedIn       int64  // todayTokensIn at last saveTokenUsage, for delta computation (#9730)
	lastSavedOut      int64  // todayTokensOut at last saveTokenUsage, for delta computation (#9730)
	sessionTokenQuota int64  // max total tokens per session; 0 = unlimited (#9438)

	// Prediction system
	predictionWorker *PredictionWorker
	metricsHistory   *MetricsHistory

	// Insight enrichment
	insightWorker *InsightWorker

	// Hardware device tracking
	deviceTracker *DeviceTracker

	// Local cluster management
	localClusters *LocalClusterManager
	clusterOpsWG  sync.WaitGroup // tracks in-flight cluster create/delete/lifecycle goroutines

	// Backend process management (for restart-from-UI)
	backendCmd *exec.Cmd
	backendMux sync.Mutex

	// activeChatEntry binds an in-progress session's cancel function to the
	// WebSocket connection that started it (#9712). handleCancelChat uses the
	// conn pointer to verify the requester owns the session before cancelling,
	// preventing cross-session CSRF/bypass attacks.
	activeChatCtxs   map[string]activeChatEntry
	activeChatCtxsMu sync.Mutex

	// dryRunSessions tracks session IDs that are in dry-run mode.
	// When a session is in this set, the kubectl proxy rejects mutating
	// commands for that session, enforcing dry-run at the server level
	// regardless of what the AI agent decides to do. (#6442)
	dryRunSessions   map[string]bool
	dryRunSessionsMu sync.RWMutex

	// Auto-update system
	updateChecker *UpdateChecker

	resourceRetryMu    sync.Mutex
	resourceRetryState map[string]clusterResourceRetryState

	// digestSequence tracks state integrity packets (#12000)
	digestSequence atomic.Int64
	stopCh         chan struct{}
	stopOnce       sync.Once

	SkipKeyValidation bool // For testing purposes

	// Event processor callback for Stellar integration
	eventProcessor EventProcessor

	// HTTP client for Stellar event forwarding (reused to avoid per-call allocation)
	stellarClient *http.Client

	// Semaphore for bounding concurrent event forwards to prevent goroutine exhaustion (#13991)
	stellarForwardSem       chan struct{}
	missionExecutionTimeout time.Duration
}

// NewServer creates a new agent server
func NewServer(cfg Config) (*Server, error) {
	kubectl, err := NewKubectlProxy(cfg.Kubeconfig)
	if err != nil {
		return nil, fmt.Errorf("failed to initialize kubectl proxy: %w", err)
	}

	// Initialize k8s client for rich cluster data queries
	k8sClient, err := k8s.NewMultiClusterClient(cfg.Kubeconfig)
	if err != nil {
		slog.Error("failed to initialize k8s client", "error", err)
		// Don't fail - kubectl functionality still works
	}

	SetClusterContextProviders(nil, k8sClient)

	// Initialize AI providers
	if err := InitializeProviders(); err != nil {
		slog.Warn("provider initialization issue", "error", err)
		// Don't fail - kubectl functionality still works without AI
	}

	// Build allowed origins list
	allowedOrigins := append([]string{}, defaultAllowedOrigins...)

	// Add custom origins from environment variable (comma-separated)
	if extraOrigins := os.Getenv("KC_ALLOWED_ORIGINS"); extraOrigins != "" {
		for _, origin := range strings.Split(extraOrigins, ",") {
			origin = strings.TrimSpace(origin)
			if origin != "" {
				allowedOrigins = append(allowedOrigins, origin)
			}
		}
	}

	// Add custom origins from CLI flag
	for _, origin := range cfg.AllowedOrigins {
		origin = strings.TrimSpace(origin)
		if origin != "" {
			allowedOrigins = append(allowedOrigins, origin)
		}
	}

	// Log non-default origins so users can verify their configuration
	if len(allowedOrigins) > len(defaultAllowedOrigins) {
		slog.Info("custom allowed origins configured", "origins", allowedOrigins[len(defaultAllowedOrigins):])
	}

	// Shared secret for authentication. When KC_AGENT_TOKEN is not set,
	// auto-generate a random token so the agent is never unauthenticated
	// by default (#9480).
	agentToken := os.Getenv("KC_AGENT_TOKEN")
	tokenExplicit := agentToken != ""
	generatedTokenFlag := os.Getenv("KC_AGENT_TOKEN_GENERATED")
	startupGeneratedToken := generatedTokenFlag == "1" || strings.EqualFold(generatedTokenFlag, "true")
	if tokenExplicit && startupGeneratedToken {
		tokenExplicit = false
		slog.Info("Agent token set (startup-generated) — origin-based bypass limited to safe status probes")
	} else if tokenExplicit {
		slog.Info("Agent token authentication enabled (from KC_AGENT_TOKEN)")
	} else {
		generated, err := generateRandomToken(autoGeneratedTokenBytes)
		if err != nil {
			return nil, fmt.Errorf("failed to generate random agent token: %w", err)
		}
		agentToken = generated
		slog.Warn("KC_AGENT_TOKEN is not set — auto-generated a random token for this session; set KC_AGENT_TOKEN to pin a shared secret (docs: https://github.com/kubestellar/console#kc-agent-bridge-self-hosted-console-to-your-clusters)")
		// Print to stderr so the operator can copy-paste it into clients.
		fmt.Fprintf(os.Stderr, "Auto-generated KC_AGENT_TOKEN for this session: %s\n", agentToken)                                                                                                             //nolint:forbidigo // intentional stderr for operator UX
		fmt.Fprintln(os.Stderr, "Set KC_AGENT_TOKEN in your shell or .env to use a persistent shared secret. See https://github.com/kubestellar/console#kc-agent-bridge-self-hosted-console-to-your-clusters") //nolint:forbidigo // intentional stderr for operator UX
	}

	// Resolve per-session token quota from env, falling back to the compiled
	// default. 0 means unlimited (operator opted out of the safety net).
	sessionQuota := defaultSessionTokenQuota
	if raw := os.Getenv(sessionTokenQuotaEnvVar); raw != "" {
		if parsed, err := strconv.ParseInt(raw, 10, 64); err == nil && parsed >= 0 {
			sessionQuota = parsed
		} else {
			slog.Warn("invalid KC_SESSION_TOKEN_QUOTA value, using default",
				"value", raw, "default", defaultSessionTokenQuota)
		}
	}
	if sessionQuota > 0 {
		slog.Info("session token quota enabled", "limit", sessionQuota)
	}

	// Resolve mission execution timeout from env, falling back to the
	// compiled default (#9482).
	missionExecutionTimeout := defaultMissionExecutionTimeout
	if raw := os.Getenv(missionTimeoutEnvVar); raw != "" {
		if parsed, err := time.ParseDuration(raw); err == nil && parsed > 0 {
			missionExecutionTimeout = parsed
			slog.Info("mission execution timeout overridden", "timeout", missionExecutionTimeout)
		} else {
			slog.Warn("invalid KC_MISSION_TIMEOUT value, using default",
				"value", raw, "default", defaultMissionExecutionTimeout)
		}
	}

	now := time.Now()
	server := &Server{
		config:                  cfg,
		kubectl:                 kubectl,
		k8sClient:               k8sClient,
		registry:                GetRegistry(),
		clients:                 make(map[*websocket.Conn]*wsClient),
		allowedOrigins:          allowedOrigins,
		agentToken:              agentToken,
		tokenExplicit:           tokenExplicit,
		sessionStart:            now,
		todayDate:               now.Format("2006-01-02"),
		activeChatCtxs:          make(map[string]activeChatEntry),
		dryRunSessions:          make(map[string]bool),
		resourceRetryState:      make(map[string]clusterResourceRetryState),
		sessionTokenQuota:       sessionQuota,
		missionExecutionTimeout: missionExecutionTimeout,
		stellarClient: &http.Client{
			Timeout: 5 * time.Second,
			Transport: &http.Transport{
				MaxIdleConnsPerHost: 2,
			},
		},
		stellarForwardSem: make(chan struct{}, 32), // maxConcurrentForwards from server_events_stream.go
	}

	server.upgrader = websocket.Upgrader{
		CheckOrigin: server.checkOrigin,
	}

	// Load persisted token usage from disk
	server.loadTokenUsage()

	// Initialize prediction system
	server.predictionWorker = NewPredictionWorker(k8sClient, server.registry, server.BroadcastToClients, server.addTokenUsage)
	server.metricsHistory = NewMetricsHistory(k8sClient, "")

	// Initialize insight enrichment
	server.insightWorker = NewInsightWorker(server.registry, server.BroadcastToClients)

	// Initialize local cluster manager with broadcast callback for progress updates
	server.localClusters = NewLocalClusterManager(server.BroadcastToClients)

	// Initialize auto-update checker
	server.updateChecker = NewUpdateChecker(UpdateCheckerConfig{
		Broadcast:      server.BroadcastToClients,
		RestartBackend: server.startBackendProcess,
		KillBackend:    server.killBackendProcess,
	})

	// Initialize device tracker with notification callback
	server.deviceTracker = NewDeviceTracker(k8sClient, func(msgType string, payload interface{}) {
		server.BroadcastToClients(msgType, payload)
		// Send native notification for device alerts
		if msgType == "device_alerts_updated" {
			if resp, ok := payload.(DeviceAlertsResponse); ok && len(resp.Alerts) > 0 {
				server.sendNativeNotification(resp.Alerts)
			}
		}
	})

	server.stopCh = make(chan struct{})

	// Start state integrity worker (#12000)
	safego.GoWith("server/state-digest-worker", server.startStateDigestWorker)

	return server, nil
}

// SetEventProcessor sets the event processor callback for Stellar integration.
// This allows the agent to forward k8s events to Stellar's notification system.
func (s *Server) SetEventProcessor(processor EventProcessor) {
	s.eventProcessor = processor
}

// Start starts the agent server
func (s *Server) Start() error {
	mux := http.NewServeMux()

	s.registerRoutes(mux)

	// Wrap the mux with CSRF middleware: state-changing requests (POST, PUT,
	// DELETE, PATCH) must include the X-Requested-With: XMLHttpRequest header.
	// GET/HEAD/OPTIONS pass through unconditionally. This mirrors the Fiber
	// middleware in pkg/api/middleware/csrf.go. See #10000.
	//
	// #10699: corsMiddleware runs outermost so that CORS headers are present
	// on every response, including CSRF rejections. Without this layer the
	// browser reports an opaque CORS error instead of showing the 403.
	// corsMiddleware also short-circuits OPTIONS preflight so it never
	// reaches requireCSRF (preflight must not carry X-Requested-With).
	handler := s.corsMiddleware(maxBodyMiddleware(requireCSRF(mux)))

	addr := fmt.Sprintf("127.0.0.1:%d", s.config.Port)
	slog.Info("KC Agent starting", "version", Version, "addr", addr)
	slog.Info("health endpoint available", "url", "http://"+addr+"/health")
	slog.Info("WebSocket endpoint available", "url", "ws://"+addr+"/ws")

	// Validate all configured API keys on startup (run in background to not delay startup)
	safego.GoWith("validate-all-keys", func() { s.ValidateAllKeys() })

	// Start kubeconfig file watcher (uses k8s client's built-in watcher)
	if s.k8sClient != nil {
		s.k8sClient.SetOnReload(func() {
			slog.Info("[Server] Kubeconfig reloaded, broadcasting to clients...")
			s.kubectl.Reload()
			clusters, current := s.kubectl.ListContexts()
			s.BroadcastToClients("clusters_updated", protocol.ClustersPayload{
				Clusters: clusters,
				Current:  current,
			})
			slog.Info("[Server] broadcasted clusters to clients", "count", len(clusters))
		})
		if err := s.k8sClient.StartWatching(); err != nil {
			slog.Error("failed to start kubeconfig watcher", "error", err)
		}
	}

	// Start prediction system
	if s.predictionWorker != nil {
		s.predictionWorker.Start()
		slog.Info("Prediction worker started")
	}
	if s.metricsHistory != nil {
		s.metricsHistory.Start(metricsHistoryTick)
		slog.Info("Metrics history started")
	}

	// Start device tracker
	if s.deviceTracker != nil {
		s.deviceTracker.Start()
		slog.Info("Device tracker started")
	}

	// Load auto-update config from settings and start if enabled
	if s.updateChecker != nil {
		mgr := settings.GetSettingsManager()
		if all, err := mgr.GetAll(); err == nil && all.AutoUpdateEnabled {
			channel := all.AutoUpdateChannel
			if channel == "" {
				channel = "stable"
			}
			s.updateChecker.Configure(true, channel)
			slog.Info("auto-update started", "channel", channel)
		}
	}

	// Use explicit timeouts to prevent Slowloris-style DoS attacks (#7262).
	const (
		serverReadHeaderTimeout = 10 * time.Second
		serverReadTimeout       = 30 * time.Second
		serverWriteTimeout      = 60 * time.Second
		serverIdleTimeout       = 120 * time.Second
	)
	srv := &http.Server{
		Addr:              addr,
		Handler:           handler,
		ReadHeaderTimeout: serverReadHeaderTimeout,
		ReadTimeout:       serverReadTimeout,
		WriteTimeout:      serverWriteTimeout,
		IdleTimeout:       serverIdleTimeout,
	}
	return srv.ListenAndServe()
}
